name: Documentation Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."
