name: Documentation Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: mattnotmitt/doxygen-action@v1.9.1
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
